repos:
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.377
    hooks:
    -   id: pyright
